# This disk will be MBR partitioned with a single, large ext4 volume.  The root
# will be mounted under global_mount_point
global_device_node: /dev/sda
global_partition_number: 1
global_mount_point: /mnt

# Initial users to create. They will all be added to the whhel group and
# allowed to call sudo (password required).
global_admins:
  - manu

# This user will be created during the setup to build AUR packages, and will be
# removed before finalizing the installation. There is no need to change the
# name.
global_passwordless_sudo_user: package_builder

global_proxy_env:
  http_proxy: "{{ http_proxy | default(omit, true) }}"
  https_proxy: "{{ https_proxy | default(omit, true) }}"
  no_proxy: "{{ no_proxy | default(omit, true) }}"

# After everything is done, remove settings which would cause the image to be
# non-portable to other systems. Currently this means removing cusom repos and
# proxy settings.
global_portable_image: False
