---
- name: Set hostname in /etc/hostname
  ansible.builtin.copy:
    content: "{{ hostname_hostname }}\n"
    dest: "{{ chroot | default('') }}/etc/hostname"
    mode: "0644"

- name: Set hostname in /etc/hosts
  ansible.builtin.lineinfile:
    regexp: "^127\\.0\\.1\\.1\\b"
    line: "127.0.1.1 {{ hostname_hostname }}.localdomain {{ hostname_hostname }}"
    state: present
    path: "{{ chroot | default('') }}/etc/hosts"
