- listen: Delete passwordless sudo user
  name: Remove passwordless sudo user from sudoers
  lineinfile:
    path: /etc/sudoers
    state: absent
    regexp: "{{ global_passwordless_sudo_user }} ALL=\\(ALL\\) NOPASSWD: ALL"
    validate: '/usr/sbin/visudo -cf %s'

- listen: Delete passwordless sudo user
  name: Delete a user that can use passwordless sudo
  user:
    name: "{{ global_passwordless_sudo_user }}"
    state: absent
    remove: yes
