---
- name: Should we use a partitioning flow
  ansible.builtin.set_fact:
    partitioning_use_flow: true
  tags: partitioning

- name: Invoke partitioning method
  ansible.builtin.include_tasks: >-
    {%- if partitioning_use_flow | default(false) -%}
        flow.yaml
    {%- else -%}
        manual.yaml
    {%- endif -%}
