---
- name: Remove custom repositories definitions
  ansible.builtin.file:
    path: /etc/pacman.d/{{ item.name }}.repo
    state: absent
  loop: "{{ custom_repos_list }}"

- name: Delete repository definitions in pacman.conf
  ansible.builtin.lineinfile:
    path: /etc/pacman.conf
    regexp: "^Include = /etc/pacman\\.d/{{ item.name | regex_escape }}\\.repo$"
    create: false
    state: absent
  loop: "{{ custom_repos_list }}"

- name: Delete custom servers
  ansible.builtin.lineinfile:
    path: /etc/pacman.d/mirrorlist
    regexp: "^Server = {{ item | regex_escape }}$"
    create: false
    state: absent
  loop: "{{ custom_repos_servers }}"
