---
- name: Copy custom repositories definitions
  ansible.builtin.copy:
    dest: /etc/pacman.d/{{ item.name }}.repo
    content: |
      [{{ item.name }}]
      Server = {{ item.server }}
      SigLevel = {{ item.siglevel }}
    mode: "0644"
  loop: "{{ custom_repos_list }}"

- name: Include repository definitions in pacman.conf
  ansible.builtin.lineinfile:
    path: /etc/pacman.conf
    regexp: "^Include = /etc/pacman\\.d/{{ item.name | regex_escape }}\\.repo$"
    line: Include = /etc/pacman.d/{{ item.name }}.repo
    create: false
    state: present
    insertbefore: ^[[]core[]]$
  loop: "{{ custom_repos_list }}"

- name: Add custom servers
  ansible.builtin.lineinfile:
    path: /etc/pacman.d/mirrorlist
    regexp: "^Server = {{ item | regex_escape }}$"
    line: "Server = {{ item }}"
    create: false
    state: present
    insertbefore: BOF
  loop: "{{ custom_repos_servers | reverse | list }}"
