---
- name: Install xorg-xev and xorg-xrandr
  ansible.builtin.import_role:
    name: packages
  vars:
    packages:
      - xorg-xev
      - xorg-xrandr

- name: Autostart xev & xrandr to resize the screen
  ansible.builtin.copy:
    src: autoresizer.desktop
    dest: /etc/xdg/autostart/
    mode: "0644"
