---
- name: Copy yay's config to user home
  become: true
  become_user: "{{ item }}"
  ansible.builtin.copy:
    src: config.json
    dest: "{{ users_created | user_home(item) }}/.config/yay/"
    mode: "0644"
  loop: "{{ users_names }}"
