---
- name: Apply virtguest settings override
  ansible.builtin.set_fact:
    ansible_virtualization_role: guest
    ansible_virtualization_type: "{{ virtguest_force }}"
  when: virtguest_force != ""
