---
- name: Create a MBR partition table and the boot partition
  community.general.parted:
    device: "{{ partitioning_priv_device_node }}"
    state: present
    label: msdos
    number: 1
    part_start: "{{ 1024 * 1024 }}B"
    part_end: "{{ partitioning_priv_boot_size | int + 1024 * 1024 - 1 }}B"
    flags:
      - boot

- name: Create the partition to hold the PV
  community.general.parted:
    device: "{{ partitioning_priv_device_node }}"
    state: present
    label: msdos
    number: 2
    part_start: "{{ partitioning_priv_boot_size | int + 1024 * 1024 }}B"
    flags:
      - lvm

- name: Enumerate created partitions
  ansible.builtin.shell: set -o pipefail && lsblk -n -o PATH {{ partitioning_priv_device_node | quote }} | tail -n +2
  register: _partitions
  changed_when: false

- name: Assign partitions to variables
  ansible.builtin.set_fact:
    partitioning_priv_boot_device_node: "{{ _partitions.stdout_lines[0] }}"
    partitioning_priv_root_device_node: "{{ _partitions.stdout_lines[1] }}"

- name: Format the boot partition
  community.general.filesystem:
    dev: "{{ partitioning_priv_boot_device_node }}"
    fstype: ext4
    opts: -O ^64bit

- name: Create a PV and VG for root
  community.general.lvg:
    vg: "{{ partitioning_priv_vg_name }}"
    pvs:
      - "{{ partitioning_priv_root_device_node }}"

- name: Create a root LV
  community.general.lvol:
    vg: "{{ partitioning_priv_vg_name }}"
    lv: "{{ partitioning_priv_lv_name }}"
    size: "100%FREE"

- name: Store root PV name
  ansible.builtin.set_fact:
    partitioning_priv_root_lv_node: >-
      /dev/{{ partitioning_priv_vg_name }}/{{ partitioning_priv_lv_name }}

- name: Format the root partition
  community.general.filesystem:
    dev: "{{ partitioning_priv_root_lv_node }}"
    fstype: ext4

- name: Mount the root partition
  ansible.posix.mount:
    state: mounted
    src: "{{ partitioning_priv_root_lv_node }}"
    path: "{{ partitioning_root_mount_point }}"
    fstype: ext4
    opts: rw,relatime

- name: Create /boot
  ansible.builtin.file:
    state: directory
    path: "{{ partitioning_root_mount_point }}/boot"
    mode: "0755"

- name: Mount the boot partition
  ansible.posix.mount:
    state: mounted
    src: "{{ partitioning_priv_boot_device_node }}"
    path: "{{ partitioning_root_mount_point }}/boot"
    fstype: ext4
    opts: rw,relatime
