---
- name: Export proxy variables from shell profile
  ansible.builtin.template:
    src: proxy.sh.j2
    dest: /etc/profile.d/proxy.sh
    mode: "0644"

- name: Pass http{,s}_proxy through sudo
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: present
    line: Defaults env_keep += "{{ global_proxy_env | list | join(' ') }}"
    validate: "/usr/sbin/visudo -cf %s"

- name: Set pacman's XferCommand to curl
  ansible.builtin.lineinfile:
    create: false
    path: /etc/pacman.conf
    backrefs: true
    regexp: "^#(XferCommand = /usr/bin/curl.*)$"
    line: "\\1"
